# Generated by Django 3.2.6 on 2021-12-04 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('location', models.CharField(choices=[('Chittagong', 'Chittagong'), ('Dhaka', 'Dhaka'), ('Sylhet', 'Sylhet'), ('Rajshahi', 'Rajshahi'), ('Barishal', 'Barishal'), ('Comilla', 'Comilla'), ('Rangpur', 'Rangpur'), ('Gazipur', 'Gazipur'), ('Narayanganj', 'Narayanganj')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'userprofile',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand', models.CharField(choices=[('Apple', 'Apple'), ('Acer', 'Acer'), ('Asus', 'Asus'), ('HP', 'HP'), ('Dell', 'Dell'), ('Lenovo', 'Lenovo'), ('Sony', 'Sony'), ('Samsung', 'Samsung'), ('Toshiba', 'Toshiba'), ('Compaq', 'Compaq'), ('Walton', 'Walton'), ('Others', 'Others')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=100)),
                ('price', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=1000, null=True)),
                ('datentime', models.DateTimeField()),
                ('image', models.ImageField(null=True, upload_to='computer_pic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
